/*
    FreeRTOS V8.2.0 - Copyright (C) 2015 Real Time Engineers Ltd.
    All rights reserved
*/

#include "shell.h"

/* Dimensions the buffer into which input characters are placed. */
#define cmdMAX_INPUT_SIZE		50

#define cmdQUEUE_LENGTH			25

/* DEL acts as a backspace. */
#define cmdASCII_DEL		( 0x7F )

#define cmdMAX_MUTEX_WAIT		( ( ( TickType_t ) 300 ) / ( portTICK_PERIOD_MS ) )


/*-----------------------------------------------------------*/

/* Data queue of USARTs */
extern xQueueHandle xQueueUART1Recvie;

/* Const messages output by the command console. */
static const char * const pcWelcomeMessage = "Wellcome to NEGLST(NEver Get LoST).\n\rType Help to view a list of registered commands.\n\r\n\r>";
static const char * const pcEndOfOutputMessage = "\r\n[Press ENTER to execute the previous command again]\n\r";
static const char * const pcNewLine = "\n";


/*-----------------------------------------------------------*/

void vUARTCommandConsoleStart( uint16_t usStackSize, UBaseType_t uxPriority )
{
	/* Create that task that handles the console itself. */
	xTaskCreate( 	prvUARTCommandConsoleTask,	/* The task that implements the command console. */
					"CLI",						/* Text name assigned to the task.  This is just to assist debugging.  The kernel does not use this name itself. */
					usStackSize,				/* The size of the stack allocated to the task. */
					NULL,						/* The parameter is not used, so NULL is passed. */
					uxPriority,					/* The priority allocated to the task. */
					NULL );						/* A handle is not required, so just pass NULL. */

	vRegisterSampleCLICommands();
}
/*-----------------------------------------------------------*/

void prvUARTCommandConsoleTask( void *pvParameters )
{
	char cRxedChar;
	uint8_t ucInputIndex = 0;
	char *pcOutputString;
	static char cInputString[ cmdMAX_INPUT_SIZE ], cLastInputString[ cmdMAX_INPUT_SIZE ];
	BaseType_t xReturned;

	( void ) pvParameters;

	/* Obtain the address of the output buffer.  Note there is no mutual
	exclusion on this buffer as it is assumed only one command console interface
	will be used at any one time. */
	pcOutputString = FreeRTOS_CLIGetOutputBuffer();

	/* Send the welcome message. */
	uprintf("%s", pcWelcomeMessage);

	for( ;; ){

		/* Wait for the next character.  The while loop is used in case
		INCLUDE_vTaskSuspend is not set to 1 - in which case portMAX_DELAY will
		be a genuine block time rather than an infinite block time. */
		while( vSerialGetChar( xQueueUART1Recvie, &cRxedChar, portMAX_DELAY ) != pdPASS );

		/* Echo the character back. */
		uprintf("%c", cRxedChar);

		/* Was it the end of the line? */
		if( cRxedChar == '\n' || cRxedChar == '\r' )
		{
			/* Just to space the output from the input. */
			uprintf("\n");

			/* See if the command is empty, indicating that the last command
			is to be executed again. */
			if( ucInputIndex == 0 )
			{
				/* Copy the last command back into the input string. */
				strcpy( cInputString, cLastInputString );
			}

			/* Pass the received command to the command interpreter.  The
			command interpreter is called repeatedly until it returns
			pdFALSE	(indicating there is no more output) as it might
			generate more than one string. */
			do
			{
				/* Get the next output string from the command interpreter. */
				xReturned = FreeRTOS_CLIProcessCommand( cInputString, pcOutputString, configCOMMAND_INT_MAX_OUTPUT_SIZE );

				/* Write the generated string to the UART. */
				uprintf("%s\n", pcOutputString);

			} while( xReturned != pdFALSE );

			/* All the strings generated by the input command have been
			sent.  Clear the input string ready to receive the next command.
			Remember the command that was just processed first in case it is
			to be processed again. */
			strcpy( cLastInputString, cInputString );
			ucInputIndex = 0;
			memset( cInputString, 0x00, cmdMAX_INPUT_SIZE );

			uprintf("%s\n>", pcEndOfOutputMessage);
		}
		else
		{
			if( cRxedChar == '\r' )
			{
				/* Ignore the character. */
			}
			else if( ( cRxedChar == '\b' ) || ( cRxedChar == cmdASCII_DEL ) )
			{
				/* Backspace was pressed.  Erase the last character in the
				string - if any. */
				if( ucInputIndex > 0 )
				{
					ucInputIndex--;
					cInputString[ ucInputIndex ] = '\0';
					uprintf("\b \b");
				}
			}
			else
			{
				/* A character was entered.  Add it to the string entered so
				far.  When a \n is entered the complete	string will be
				passed to the command interpreter. */
				if( ( cRxedChar >= ' ' ) && ( cRxedChar <= '~' ) )
				{
					if( ucInputIndex < cmdMAX_INPUT_SIZE )
					{
						cInputString[ ucInputIndex ] = cRxedChar;
						ucInputIndex++;
					}
				}
			}
		}		
	}
}
/*-----------------------------------------------------------*/